# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Tell Read the Docs to use MkDocs
mkdocs:
  configuration: mkdocs.yml

# Install our requirements (MkDocs)
python:
   install:
   - requirements: requirements.txt
